include ../config

CFLAGS		+= -DKHZ=4608 #4096
TESTS		= demo1.sre demo2.sre demo4.sre

all:		$(TESTS)
		avr-size *.out

1:		demo1.out demo1.sre
		$(ISP) if=demo$@.sre

2:		demo2.out demo2.sre
		$(ISP) if=demo$@.sre

3:		demo3.out demo3.sre
		$(ISP) if=demo$@.sre

4:		demo4.out demo4.sre
		$(ISP) if=demo$@.sre

clean:
		rm -f *.out *.hex *.sre *.[osi] *.lst *.dis *~

###
